default: &default
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  database: chat_ror_development

test:
  <<: *default
  database: chat_ror_test

production:
  <<: *default
  database: chat_ror_production
  username: chat_ror
  password: <%= ENV['CHAT_ROR_DATABASE_PASSWORD'] %>